---
version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
  disable:
    - errcheck
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: '(.+)\.go$'
        text: "(Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)"
      - path: '(.+)\.go$'
        text: "Potential file inclusion via variable"
      - path: '(.+)\.go$'
        text: "G306: Expect WriteFile permissions to be 0600 or less"
      - path: '(.+)\.go$'
        text: "avoid meaningless package names"
  settings:
    gocyclo:
      min-complexity: 18
    govet:
      enable:
        - shadow
    lll:
      line-length: 200
formatters:
  enable:
    - gofmt
    - goimports
run:
  timeout: 5m

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
